### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by zubus** [gabomdq/pytgvoip#4]
Hi, I know this is old, but, is still working? come here from your blog and I need to do the same.

Thanks

**Comment by gabomdq** [comment]
I haven't tested this in a while, so I don't know :)

**Comment by chweyakevin** [comment]
Did you find a better alternative @gabomdq

**Comment by chweyakevin** [comment]
@gabomdq It is actually amazing you took time to write a blog about it. At least you give some one or two people like me hope, when we get stuck. There are so many "Telegram API Wrappers" that claim to do so much and that is a nightmare for developers because it is hard to settle one and not the other, and you end up testing over 10 libraries, frameworks etc.
